### PR TITLE
cleaned up CompareUtils

### PR DESCRIPTION
**Pull request by cjunxiang**

### CODE REVIEW

**Comment by cjunxiang** [comment]
Codacy leaving some useless comments. @arjo129 @shuanang @TTTaus need advice on whether we shld go on with underscores in test name LOL

**Comment by shuanang** [comment]
Try name_test instead of name_Test?

**Comment by TTTaus** [comment]
@shuanang yea I think its lowercase

**Comment by shuanang** [comment]
nice!

**Pull request merged**
